main/models.py
#-*-coding:utf-8-*-
from flask_sqlalchemy import SQLAlchemy
db = SQLAlchemy()
from main.ext import bcrypt
from flask_login import AnonymousUserMixin
from .ext import login_manager
from flask import current_app
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer

"""
建立数据模型
"""
class User(db.Model):
    __tablename__="user"
    id = db.Column(db.Integer(),primary_key=True)
    username = db.Column(db.String(255))
    password = db.Column(db.String(255))
    email = db.Column(db.String(255))
    confirmed = db.Column(db.Boolean,default=False)
    posts = db.relationship(
        "Post",
        backref = "user",
        lazy = "dynamic"
    )

    def __init__(self,username):
        self.username = username
    def __repr__(self):
        return "<User %s>".format(self.username)
    def set_password(self,password):
        self.password = bcrypt.generate_password_hash(password)
    def check_password(self,password):
        return bcrypt.check_password_hash(self.password,password)
    def is_authenticated(self):
        if isinstance(self,AnonymousUserMixin):
            return False
        else:
            return True
    def is_active(self):
        return True
    def is_anonymous(self):
        if isinstance(self,AnonymousUserMixin):
            return False
        else:
            return True
    def get_id(self):
        return self.id
    def gengerate_confirm(self,expiration=3600):
        s = Serializer(current_app.config["SECRET_KEY"],expiration)
        return s.dumps({"confirm":self.id})
    def confirm(self,token):
        s = Serializer(current_app.config["SECRET_KEY"])
        try:
            data = s.loads(token)
        except:
            return False
        if data.get("confirm")!=self.id:
            return False
        self.confirmed = True
        db.session.add(self)
        return True
tags =  db.Table("post_tag",
                 db.Column("post_id",db.Integer,db.ForeignKey("post.id")),
                 db.Column("tag_id",db.Integer,db.ForeignKey("tag.id"))
                 )

@login_manager.user_loader
def load_user(userid):
    return User.query.get(userid)

class Post(db.Model):
    __tablename__="post"
    id = db.Column(db.Integer(),primary_key=True)
    title = db.Column(db.String(255),index=True)
    text = db.Column(db.Text())
    publish_date = db.Column(db.DateTime())
    comments = db.relationship(
        "Comment",
        backref="post",
        lazy="dynamic"
    )
    user_id = db.Column(db.Integer(),db.ForeignKey("user.id"))
    tags = db.relationship("Tag",
                           secondary=tags,
                           backref=db.backref("posts",lazy="dynamic")
                           )

    def __init__(self,title):
        self.title = title

    def __repr__(self):
        return "<Post %s>".format(self.title)

class Comment(db.Model):
    __tablename__="comment"
    id = db.Column(db.Integer(),primary_key=True)
    name = db.Column(db.String(255))
    text = db.Column(db.Text())
    date = db.Column(db.DateTime())
    post_id = db.Column(db.Integer(),db.ForeignKey("post.id"))

    def __repr__(self):
        return "<Comment %s>".format(self.text[:15])

class Tag(db.Model):
    __tablename__="tag"
    id = db.Column(db.Integer(),primary_key=True)
    title = db.Column(db.String(255),index=True)

    def __init__(self,title):
        self.title=title

    def __repr__(self):
        return "<Tag %s>".format(self.title)

main/forms.py
#-*-coding:utf-8-*-
from flask_wtf import Form
from wtforms import StringField,SelectField,TextAreaField,PasswordField,BooleanField,SubmitField
from wtforms.validators import DataRequired,Length,Email,Regexp,EqualTo
from main.models import User
from wtforms import ValidationError

class CommentForm(Form):
    name = StringField(
        "名字",
        validators=[DataRequired(),Length(max=255)]
    )
    text = TextAreaField(u"评论",validators=[DataRequired()])

class LoginForm(Form):
    username = StringField("姓名",
                         [DataRequired(),Length(max=255)])
    password = PasswordField("密码",[DataRequired()])

    remeber = BooleanField("记住登录状态")

    submit = SubmitField("登录")
    def validate(self):
        check_validate = super(LoginForm,self).validate()

        #验证没通过
        if not check_validate:
            return False
        #检查是否存在拥有该用户名的用户
        user = User.query.filter_by(
            username = self.username.data
        ).first()
        if not user:
            self.username.errors.append(
                "未找到用户名"
            )
            return False
        #检查密码是否匹配
        if not user.check_password(self.password.data):
            self.username.errors.append(
                "错误的密码"
            )
            return False
        return True

class RegistrationForm(Form):
    email = StringField("邮件",validators=[DataRequired(),Length(max=255),Email()])
    username = StringField("用户名",validators=[DataRequired(),Length(max=255),
                                             Regexp('^[A-Za-z][A-Za-z0-9_.]*$', 0,
'Usernames must have only letters,'
'numbers, dots or underscores')])
    password = PasswordField("密码",validators=[DataRequired(),Length(1,255),EqualTo("password2",message="两次密码好像不符")])
    password2 = PasswordField("重复密码",validators=[DataRequired()])
    submit = SubmitField("注册用户")

    def validate_email(self,field):
        if User.query.filter_by(email = field.data).first():
            raise ValidationError("该邮箱已注册")
    def validate_usernme(self,field):
        if User.query.filter_by(usernmae = field.data).first():
            raise ValidationError("该用户名已注册")
class PostForm(Form):
    title = StringField("文章名称",[DataRequired(),Length(max=255)])
    text = TextAreaField("文章内容",[DataRequired(255)])
    publish_date = StringField("发表时间",[DataRequired(255)])
    comments = StringField("评论",[DataRequired(255)])
    user = StringField("作者",[DataRequired(255)])
    tag = StringField("标签",[DataRequired(255)])
    submit = SubmitField("完稿",[DataRequired(255)])

main/__init__.py
#-*-coding:utf-8-*-

from flask import Flask,redirect,url_for
# import blurprint
from main.module.home import home_blueprint
from main.module.about import about_blueprint
from main.module.contact import contact_blueprint
from main.module.services import services_blueprint
from main.module.work import work_blueprint
from main.module.blog import blog_blueprint
from main.module.auth import auth_blueprint
# import var
from main.models import db
# import ext
from main.ext import bcrypt
from main.ext import bootstrap
from main.ext import login_manager
from main.ext import mail
"""
:param object_name
:return app
"""
def create_app(object_name):
    app = Flask(__name__)
    app.config.from_object(object_name)
    #register blueprint
    app.register_blueprint(home_blueprint)
    app.register_blueprint(about_blueprint)
    app.register_blueprint(contact_blueprint)
    app.register_blueprint(services_blueprint)
    app.register_blueprint(work_blueprint)
    app.register_blueprint(blog_blueprint)
    app.register_blueprint(auth_blueprint)
    #instance
    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)
    bootstrap.init_app(app)
    mail.init_app(app)
    @app.route("/")
    def index():
        return redirect(url_for("home.home_index"))
    return app

main/ext/__init__.py
#-*-coding:utf-8-*-
from flask_bcrypt import Bcrypt
bcrypt = Bcrypt()

from flask_bootstrap import Bootstrap
bootstrap = Bootstrap()

from flask_mail import Mail
mail=Mail()

from flask_login import LoginManager
login_manager = LoginManager()
login_manager.login_view="auth.login_index"
login_manager.session_protection="strong"
login_manager.login_message="登录以获得更多功能"
login_manager.login_message_category="info"

main/module/about/__init__.py
#-*-coding:utf-8-*-

from flask import Blueprint

about_blueprint = Blueprint(
    'about',
    __name__,
    url_prefix = "/about"
)

from . import views

main/module/about/views.py
#-*-coding:utf-8-*-

from . import about_blueprint
from flask import render_template

@about_blueprint.route("/")
def about_index():
    return render_template("about.html")

main/module/blog/__init__.py
#-*-coding:utf-8-*-

from flask import Blueprint

blog_blueprint = Blueprint(
    'blog',
    __name__,
    url_prefix = "/blog"
)

from . import views

main/module/blog/views.py
#-*-coding:utf-8-*-

from . import blog_blueprint
from flask import render_template
from main.forms import CommentForm
from main.models import Post

"""
主要展示好评、推荐文章
"""
@blog_blueprint.route("/")
def blog_index():
    return render_template("blog.html")

"""
主要展示所有文章，只按发表时间顺序
"""
@blog_blueprint.route("/post_list")
def post_list():
    post_list = Post.query.order_by(Post.publish_date.desc()).all()
    return render_template("blog/post.html",post=post)

"""
显示单个文章
"""
@blog_blueprint.route("/post_list/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template("blog/post.html", post=post)

"""
显示单个文章的用户操作
"""
@blog_blueprint.route("/post_list/<int:post_id>/<string:control>")
def post_id_control():
    pass

main/module/contact/__init__.py
#-*-coding:utf-8-*-

from flask import Blueprint

contact_blueprint = Blueprint(
    'contact',
    __name__,
    url_prefix = "/contact"
)

from . import views

main/module/contact/views.py
#-*-coding:utf-8-*-

from . import contact_blueprint
from flask import render_template

@contact_blueprint.route("/")
def contact_index():
    return render_template("contact.html")

main/module/home/__init__.py
#-*-coding:utf-8-*-

from flask import Blueprint

home_blueprint = Blueprint(
    'home',
    __name__,
    url_prefix = "/home"
)

from . import views

main/module/home/views.py
#-*-coding:utf-8-*-

from . import home_blueprint
from flask import render_template,send_file,make_response
import os
import sys


@home_blueprint.route("/")
def home_index():
    return render_template("index.html")


""""
下载简历
:param none
:return response
"""
@home_blueprint.route("/resume")
def home_resume():
    sys.stdout.buffer.write(chr(9986).encode('utf8'))
    resume_route=os.path.join(os.getcwd(),r"file",r"linhanqiu.pdf")
    response = make_response(send_file(resume_route))
    response.headers["Content-Disposition"] = "attachment; filename=林韩秋的简历.pdf;"
    return response

main/module/services/__init__.py
#-*-coding:utf-8-*-

from flask import Blueprint

services_blueprint = Blueprint(
    'services',
    __name__,
    url_prefix = "/services"
)

from . import views

main/module/services/views.py
#-*-coding:utf-8-*-

from . import services_blueprint
from flask import render_template

@services_blueprint.route("/")
def services_index():
    return render_template("services.html")

main/module/work/__init__.py
#-*-coding:utf-8-*-

from flask import Blueprint

work_blueprint = Blueprint(
    'work',
    __name__,
    url_prefix = "/work"
)

from . import views

main/module/work/views.py
#-*-coding:utf-8-*-

from . import work_blueprint
from flask import render_template

@work_blueprint.route("/")
def work_index():
    return render_template("work.html")

main/templates/about.html
<!DOCTYPE HTML>
<html>
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
                <Link Rel="SHORTCUT ICON" href="../static/images/title1.jpg">
	<title>Shape &mdash; 林韩秋的介绍系统</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Free HTML5 Website Template by FreeHTML5.co" />
	<meta name="keywords" content="free website templates, free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive" />
	<meta name="author" content="FreeHTML5.co" />



  	<!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<link href='https://fonts.googleapis.com/css?family=Work+Sans:400,300,600,400italic,700' rel='stylesheet' type='text/css'>

	<!-- Animate.css -->
	<link rel="stylesheet" href="../static/css/animate.css">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="../static/css/icomoon.css">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="../static/css/bootstrap.css">

	<!-- Magnific Popup -->
	<link rel="stylesheet" href="../static/css/magnific-popup.css">

	<!-- Theme style  -->
	<link rel="stylesheet" href="../static/css/style.css">

	<!-- Modernizr JS -->
	<script src="../static/js/modernizr-2.6.2.min.js"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="static/js/respond.min.js"></script>
	<![endif]-->

	</head>
	<body>

	<div class="fh5co-loader"></div>

	<div id="page">
	<nav class="fh5co-nav" role="navigation">
		<div class="container">
			<div class="row">
				<div class="col-xs-12 text-center">
					<div id="fh5co-logo"><a href="index.html">Shape<span>.</span></a></div>
				</div>
				<div class="col-xs-12 text-center menu-1">
					<ul>
						<li><a href={{ url_for("home.home_index") }}>Home</a></li>
						<li class="has-dropdown">
							<a href={{ url_for("services.services_index") }}>Services</a>
							<ul class="dropdown">
								<li><a href="#">Web Robot 网页机器人</a></li>
								<li><a href="#">Demo Show 渣渣原型，新手可进</a></li>
								<li><a href="#">Join PSC 加入我们</a></li>
								<li><a href="#">搜索来的API</a></li>
							</ul>
						</li>

						<li><a href={{ url_for("work.work_index") }}>Work</a></li>
						<li class="active"><a href={{ url_for("about.about_index") }}>About</a></li>
						<li><a href={{ url_for("blog.blog_index") }}>Blog</a></li>
						<li><a href={{ url_for("contact.contact_index") }}>Contact</a></li>
                        <li><a href={{ url_for("auth.logout_index") }}>Logout</a></li>

					</ul>
				</div>
			</div>

		</div>
	</nav>

	<header id="fh5co-header" class="fh5co-cover" role="banner" style="background-image:url(../static/images/bg.jpg);">
		<div class="overlay"></div>
		<div class="container">
			<div class="row">
				<div class="col-md-12 col-md-offset-0 text-center">
					<div class="display-t">
						<div class="display-tc animate-box" data-animate-effect="fadeInUp">
							<h1 class="mb30">About Me</h1>
						</div>
					</div>
				</div>
			</div>
		</div>
	</header>

	

	<div id="fh5co-about">
		<div class="container">
				<div class="row row-pb-md">
					<div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
						<span>Know Me</span>
						<h2>林韩秋</h2>
						<p>湖南湘潭大学2017届毕业生，本科学习的是信息管理与信息系统专业，主修计算机基础、数据库基础、计算机网络基础、数据结构、软件工程。</p>
					</div>
				</div>
				<div class="row row-pb-md animate-box">
					<div class="col-md-6 col-md-push-6">
						
						<div class="desc">
							<h3>自我能力评价</h3>
							<ul>
                                <li>1.自身对互联网保持高度的敏感性和关注度,熟悉软件开发流程,专研能力强,具备较强的沟通协作能力,有较强的团队合作精神和敬业精神；</li>
                                <li>2.熟悉git 、jenkins操作,能使用git 进行版本控制的合作以及jenkins快速迭代开发;</li>
                                <li>3.熟悉DBMS、RDBMS数据库,有过亿万级数据库的管理、操作经验;</li>
                                <li>4.熟悉pyt hon2、3、ruby等开发语言,了解常用开源框架(Flask、Scrapy、Twist ed、aioht t p)使用;</li>
                                <li>5.熟悉常用的数据结构、排序算法等;</li>
                                <li>6.对于数据库以及服务器集群、缓存、负载均衡等分布式系统架构有所了解;</li>
                                <li>7.对于爬虫技术有所了解。</li>
                                <li>8.喜欢开源项目,正在建立Python开源项目的项目组PSC;</li>
                            </ul>
							<p></p>
						</div>
					</div>
					<div class="col-md-6 col-md-pull-6">
						<img class="img-responsive" src="../static/images/black.jpg" alt="about">
					</div>
					
				</div>
			
		</div>
	</div>

	<div id="fh5co-team" class="fh5co-bg-section">
		<div class="container">
			<div class="row animate-box">
				<div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
					<span>工作经历</span>
					<h2>实习以及正式</h2>
					<p>包括两家实习公司以及一家最近离职的公司</p>
				</div>
			</div>
			<div class="row">
				<div class="col-md-4 col-sm-4 animate-box" data-animate-effect="fadeIn">
					<div class="fh5co-staff">
						<img src="../static/images/quanshi.jpg" alt="Free HTML5 Templates by gettemplates.co">
						<h3>北京全时云商务有限公司（2016.7-2016.8）</h3>
						<strong class="role">Linux系统运维实习生</strong>
                        <ul>
                            <li>
                                1.负责Linux/Unix平台下服务器的规划、使用、维护;
                            </li>
                            <li>
                                2.配合建设自动化运维系统、研发小型管理工具;
                            </li>
                            <li>
                                3.全方位的系统、网络性能监控、优化;
                            </li>
                            <li>
                                4 .参与Hadoop相关项目的环境配置和实施工作。
                            </li>
                        </ul>

					</div>
				</div>
				<div class="col-md-4 col-sm-4 animate-box" data-animate-effect="fadeIn">
					<div class="fh5co-staff">
						<img src="../static/images/jinshanyun.jpg" alt="Free HTML5 Templates by gettemplates.co">
						<h3>北京金山云科技有限公司（2016.9-2017.3）</h3>
						<strong class="role">Python服务器开发实习生</strong>
                        <ul>
                            <li>
                                1、负责编写金山企业云网盘的需求文档和用户体验文档;
                            </li>
                            <li>
                                2、使用pyt hon搭建Web服务器日志分析处理系统,并可视化界面展示;
                            </li>
                            <li>
                                3、配置金山企业云网盘一体机产品配置;
                            </li>
                            <li>
                                4 、负责金山企业云网盘控制台功能开发工作。
                            </li>
                        </ul>

					</div>
				</div>
				<div class="col-md-4 col-sm-4 animate-box" data-animate-effect="fadeIn">
					<div class="fh5co-staff">
						<img src="../static/images/youliwang.jpg" alt="Free HTML5 Templates by gettemplates.co">
						<h3>北京有利网</h3>
						<strong class="role">Python安全开发工程师</strong>
                        <ul>
                            <li>
                                1、独立开发腾讯企业邮件日志记录分析系统;
                            </li>
                            <li>
                                2、参与“快闪现金”风控系统的开发;
                            </li>
                            <li>
                                3、有利网数据库数据存储转换脚本的开发;
                            </li>
                            <li>
                                4 、搭建git hub爬虫,实时检测资料外泄;
                            </li>
                        </ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	
	

	<div id="fh5co-testimonial" class="fh5co-bg-section">
		<div class="container">
			<div class="row animate-box row-pb-md">
				<div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
					<span>项目经验</span>
					<h2>个人以及公司项目</h2>
				</div>
			</div>
			<div class="row">
				<div class="col-md-6 animate-box">
					<div class="testimonial">
						<blockquote>
							<p>&ldquo;有利网任职期间,开发的基于aioht t p、pyt hon3开发的有利网-“快闪现金”项目的风控系统模块,模块主要功能为可视化管理风控组的特征变量以及flag,加速风控规则的上线时间和运行稳定性;.&rdquo;</p>
							<p class="author"> <img src="../static/images/person1.jpg" alt="Free HTML5 Bootstrap Template by FreeHTML5.co"> <cite>&mdash; 有利网-快闪现金风控系统开发</cite></p>
						</blockquote>
					</div>

					<div class="testimonial">
						<blockquote>
							<p>&ldquo;有利网任职期间,开发的基于flask框架、celery队列框架、NLTK数分处理模块搭建的日志记录分析系统,提供风险ip报告、异常邮件源分析等功能;.&rdquo;</p>
							<p class="author"><img src="../static/images/person2.jpg" alt="Free HTML5 Bootstrap Template by FreeHTML5.co"> <cite>&mdash; 有利网-企业邮件日志记录系统开发</cite></p>
						</blockquote>
					</div>
				</div>

				<div class="col-md-6 animate-box">
					<div class="testimonial">
						<blockquote>
							<p>&ldquo;金山网盘任职期间,开发的基于flask系统的非实时分析nginx服务集群日志系统;金山网盘任职期间,开发的基于flask和py脚本实时分析网盘服务器状况的运维监控系统;.&rdquo;</p>
							<p class="author"><img src="../static/images/person3.jpg" alt="Free HTML5 Bootstrap Template by FreeHTML5.co"> <cite>&mdash; 金山云-企业网盘运维记录系统开发</cite></p>
						</blockquote>
					</div>

					<div class="testimonial">
						<blockquote>
							<p>&ldquo;个人毕设项目,基于scrapy框架、redis集群作缓存队列框架、mongodb集群作底层存储开发的爬虫模块结合jieba、sklearn、NLTK进行数据处理、分析的全套实时新闻处理系统.&rdquo;</p>
							<p class="author"><img src="../static/images/person1.jpg" alt="Free HTML5 Bootstrap Template by FreeHTML5.co"> <cite>&mdash; 个人项目-新闻爬虫系统开发</cite></p>
						</blockquote>
					</div>
				</div>
                <div class="col-md-6 animate-box">
					<div class="testimonial">
						<blockquote>
							<p>&ldquo;个人日常项目，基于scrapy框架，结合redis、mongodb作处理存储，并开发了大量的download中间件用以应对反爬机制.&rdquo;</p>
							<p class="author"><img src="../static/images/person3.jpg" alt="Free HTML5 Bootstrap Template by FreeHTML5.co"> <cite>&mdash; 个人项目-分布式爬虫系统开发</cite></p>
						</blockquote>
					</div>

					<div class="testimonial">
						<blockquote>
							<p>&ldquo;个人日常项目，基于flask框架，使用redis记录用户状态以及在线情况，开发了权限管理模块，类似于segmentfault的标签类论坛管理网站.&rdquo;</p>
							<p class="author"><img src="../static/images/person1.jpg" alt="Free HTML5 Bootstrap Template by FreeHTML5.co"> <cite>&mdash; 个人项目-多功能论坛系统开发</cite></p>
						</blockquote>
					</div>
				</div>
			</div>
		</div>
	</div>

	<footer id="fh5co-footer" role="contentinfo">
		<div class="container">
			<div class="row row-pb-md">
				<div class="col-md-4 fh5co-widget ">
					<h3>Shape.</h3>
					<p>Shape yourself, and I believe that everyone will have the same idea. From now on, define yourself and shape yourself.</p>
					<p><a href="#">Learn More</a></p>
				</div>
				<div class="col-md-2 col-sm-4 col-xs-6 col-md-push-1 ">
					<ul class="fh5co-footer-links">
						<li><a href="https://pan.baidu.com/s/1mi9R8vu">百度网盘学习资料</a></li>
						<li><a href="http://www.jianshu.com/u/e9fdf09df277">简书链接</a></li>
						<li><a href="http://blog.csdn.net/maliao1123">CSDN博客</a></li>
						<li><a href="https://github.com/linhanqiuinc24">个人github</a></li>
						<li><a href="https://github.com/PythonScientists">PSCgithub</a></li>
					</ul>
				</div>

				<div class="col-md-2 col-sm-4 col-xs-6 col-md-push-1 ">
					<ul class="fh5co-footer-links">
						<li><a href="#">Shop</a></li>
						<li><a href="#">Privacy</a></li>
						<li><a href="#">Testimonials</a></li>
						<li><a href="#">Handbook</a></li>
						<li><a href="#">Held Desk</a></li>
					</ul>
				</div>

				<div class="col-md-2 col-sm-4 col-xs-6 col-md-push-1 ">
					<ul class="fh5co-footer-links">
						<li><a href="#">Find Designers</a></li>
						<li><a href="#">Find Developers</a></li>
						<li><a href="#">Teams</a></li>
						<li><a href="#">Advertise</a></li>
						<li><a href="#">API</a></li>
					</ul>
				</div>
			</div>

			<div class="row copyright">
				<div class="col-md-12 text-center">
					<p>
						<small class="block">&copy; 2017 Shape. All Rights Reserved.</small>
					</p>
					<p>
						<ul class="fh5co-social-icons">
							<li><a href="#"><i class="icon-twitter"></i></a></li>
							<li><a href="#"><i class="icon-facebook"></i></a></li>
							<li><a href="#"><i class="icon-linkedin"></i></a></li>
							<li><a href="#"><i class="icon-dribbble"></i></a></li>
						</ul>
					</p>
				</div>
			</div>

		</div>
	</footer>
	</div>

	<div class="gototop js-top">
		<a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
	</div>
	
	<!-- jQuery -->
	<script src="../static/js/jquery.min.js"></script>
	<!-- jQuery Easing -->
	<script src="../static/js/jquery.easing.1.3.js"></script>
	<!-- Bootstrap -->
	<script src="../static/js/bootstrap.min.js"></script>
	<!-- Waypoints -->
	<script src="../static/js/jquery.waypoints.min.js"></script>
	<!-- countTo -->
	<script src="../static/js/jquery.countTo.js"></script>
	<!-- Magnific Popup -->
	<script src="../static/js/jquery.magnific-popup.min.js"></script>
	<script src="../static/js/magnific-popup-options.js"></script>
	<!-- Main -->
	<script src="../static/js/main.js"></script>

	</body>
</html>


main/templates/login.html
{#<html>#}
{#<div class="col-lg-12">#}
{#    <h3>登录</h3>#}
{#    <form method="post" action="{{ url_for("auth.login_index") }}">#}
{#    {{ form.hidden_tag }}#}
{#        <div class="form-group">#}
{#            {{ form.username.label }}#}
{#            {% if form.username.errors %}#}
{#                {% for e in form.username.errors %}#}
{#            <p class="form-control">{{ e }}</p>#}
{#                {% endfor %}#}
{#            {% else %}#}
{#            {{ form.username(class_="form_control") }}#}
{#            {% endif %}#}
{#        </div>#}
{#        <div class="form-group">#}
{#            {{ form.password.label }}#}
{#            {% if form.password.errors %}#}
{#                {% for e in form.password.errors %}#}
{#            <p class="form-control">{{ e }}</p>#}
{#                {% endfor %}#}
{#            {% else %}#}
{#            {{ form.password(class_="form_control") }}#}
{#            {% endif %}#}
{#        </div>#}
{#        <div class="form-group">#}
{#            {{ form.remeber.label }}#}
{#            {% if form.remeber.errors %}#}
{#                {% for e in form.remeber.errors %}#}
{#            <p class="form-control">{{ e }}</p>#}
{#                {% endfor %}#}
{#            {% else %}#}
{#            {{ form.remeber(class_="form_control") }}#}
{#            {% endif %}#}
{#        </div>#}
{#        <input class="btn btn-primary" type="submit" value="登录">#}
{#    </form>#}
{#</div>#}
{#</html>#}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_content %}
<div class="page-header">
<h1>登录</h1>
</div>
<div class="col-md-4">
{{ wtf.quick_form(form) }}
</div>
    <p>
        初次观赏?
<a href="{{ url_for('auth.register') }}">
请点此注册给我一个建议吧</a>
</p>
{% endblock %}